part_d_num_to_str = {0: "Background",
1: "Apparel",
2: "Face_Neck",
3: "Hair",
4: "Left_Foot",
5: "Left_Hand",
6: "Left_Lower_Arm",
7: "Left_Lower_Leg",
8: "Left_Shoe",
9: "Left_Sock",
10: "Left_Upper_Arm",
11: "Left_Upper_Leg",
12: "Lower_Clothing",
13: "Right_Foot",
14: "Right_Hand",
15: "Right_Lower_Arm",
16: "Right_Lower_Leg",
17: "Right_Shoe",
18: "Right_Sock",
19: "Right_Upper_Arm",
20: "Right_Upper_Leg",
21: "Torso",
22: "Upper_Clothing",
23: "Lower_Lip",
24: "Upper_Lip",
25: "Lower_Teeth",
26: "Upper_Teeth",
27: "Tongue" }

part_d_str_to_num = {v:k for (k, v) in part_d_num_to_str.items()}